# Generated by Django 5.0.3 on 2024-07-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_status', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile')),
            ],
        ),
    ]
