# Generated by Django 5.0.3 on 2024-07-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cardetail_blue_book'),
        ('users', '0002_distributorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorrequest',
            name='car_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.cardetail'),
        ),
    ]
