# Generated by Django 5.0.3 on 2024-08-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cardetail_renter_alter_carorder_product_and_more'),
        ('users', '0004_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrequest',
            name='car_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cardetail'),
        ),
        migrations.AlterField(
            model_name='distributorrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
