# Generated by Django 5.0.3 on 2024-07-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carorder_rentee'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='rentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile'),
        ),
    ]
