# Generated by Django 5.0.3 on 2024-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carorder_rentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True),
        ),
    ]
