# Generated by Django 5.0.3 on 2024-07-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carorder_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='renter_contact',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='renter_name',
        ),
        migrations.AddField(
            model_name='cardetail',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
