# Generated by Django 5.0.3 on 2024-07-25 11:21

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_cardetail_renter_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='blue_book',
            field=models.ImageField(blank=True, upload_to=cars.models.car_blue_book_path),
        ),
    ]
