# Generated by Django 5.0.3 on 2024-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cardetail_blue_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='image',
            field=models.ImageField(default='static/images/lambo.jpg', upload_to='car_images/'),
        ),
    ]
