# Generated by Django 5.0.3 on 2024-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cardetail_renter_alter_carorder_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='car_type_logo')),
            ],
        ),
    ]
