# Generated by Django 5.0.3 on 2024-08-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_cartype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carorder',
            old_name='product',
            new_name='car_detail',
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype'),
        ),
    ]
