# Generated by Django 5.0.3 on 2024-08-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_product_carorder_car_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartype',
            old_name='car_type',
            new_name='name',
        ),
    ]
